[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "lib2"
authors = [{name = "Tim Paine", email = "t.paine154@gmail.com"}]
description=""
version = "0.1.0"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
keywords = []
dependencies = [
  "lib1==0.1.0",
]

[project.optional-dependencies]
develop = [
    "black>=23",
    "bump2version",
    "check-manifest",
    "maturin>=1,<2",
    "pytest",
    "pytest-cov",
    "ruff",
    "twine",
    "wheel",
]
test = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Repository = ""
Homepage = ""

[tool.black]
color = true
line-length = 150
target-version = ['py310']
skip-string-normalization = true

[tool.check-manifest]
ignore = []

[tool.maturin]
module-name = "lib2"

[tool.ruff]
line-length = 150

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403"]

