[workspace]
members = [
  "lib2",
  "lib2-py",
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
lib1 = {version ="*", path="../../lib1/rust/lib1"}
lib1_py = {version ="*", path="../../lib1/rust/lib1-py"}
